use std::fs;

#[test]
fn test_schema_generation() {
    // Check that tool_schema.json exists (should be generated by make schema)
    let metadata = fs::metadata("tool_schema.json");
    assert!(metadata.is_ok(), "tool_schema.json should exist. Run 'make schema' first.");

    // Read and parse the schema
    let content = fs::read_to_string("tool_schema.json").expect("Failed to read tool_schema.json");
    let schemas: serde_json::Value = serde_json::from_str(&content).expect("Failed to parse JSON");

    // Verify it's an array with at least one tool
    assert!(schemas.is_array(), "Schema should be an array");
    let tools = schemas.as_array().unwrap();
    assert!(!tools.is_empty(), "Should have at least one tool");

    // Check the first tool has required fields
    let first_tool = &tools[0];
    assert!(first_tool.get("name").is_some(), "Tool should have name");
    assert!(first_tool.get("description").is_some(), "Tool should have description");
    assert!(first_tool.get("inputSchema").is_some(), "Tool should have inputSchema");
    assert!(first_tool.get("outputSchema").is_some(), "Tool should have outputSchema");

    // Verify the tool name matches expected
    let name = first_tool.get("name").unwrap().as_str().unwrap();
    assert_eq!(name, "get_weather", "First tool should be get_weather");

    // Verify input schema has location field
    let input_schema = first_tool.get("inputSchema").unwrap();
    let properties = input_schema.get("properties").unwrap();
    assert!(properties.get("location").is_some(), "Input schema should have location property");

    // Verify output schema has required fields
    let output_schema = first_tool.get("outputSchema").unwrap();
    let output_properties = output_schema.get("properties").unwrap();
    assert!(output_properties.get("temperature").is_some(), "Output schema should have temperature");
    assert!(output_properties.get("weather_code").is_some(), "Output schema should have weather_code");
    assert!(output_properties.get("wind_speed").is_some(), "Output schema should have wind_speed");
}